// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("static_observer")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/staticobserver"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
